### ISSUE TITLE
Add Dennis to Dockerfiles team

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/Unidata-Dockerfiles#20]
Could someone add @DennisHeimbigner to @Unidata/team-unidata-dockerfiles? I am not setup to be a team maintainer for that team.

Thanks!

Sean

**Comment by julienchastang** [comment]
Done.

**Comment by lesserwhirls** [comment]
Thanks!

**Comment by DennisHeimbigner** [comment]
Thanks!
=Dennis

Julien Chastang wrote:

**Comment by julienchastang** [comment]
@lesserwhirls @DennisHeimbigner Just one other thought here. Let's just all be mindful that we use each others stuff (I depend on the TDS dockerfiles for example), so if possible please make commits via pull requests, etc. when there is the possibility of stepping on each others toes. Thanks!

**Comment by DennisHeimbigner** [comment]
ok; is there a specific person responsible for accepting pull requests,
or is it ok if we do it ourselves (even if we are the submitter)
=Dennis

**Comment by julienchastang** [comment]
There is no specific person, and as best we can I think we will just have to use common sense. I also think it is OK if submitters commit their own PRs, as long as there is a bit of lag for others to see what is up. Thanks again.
