### ISSUE TITLE
JupyterHub user storage

### ISSUE THREAD

**Issue by dopplershift** [Unidata/Unidata-Dockerfiles#4]
Need to see how we can store user data (volumes) on a separate AWS partition so that it's portable across instances. Or maybe _that's_ a good reason to investigate storing the stuff on an S3 bucket. 
- [ ] Decide upon a storage solution (S3/EBS)
- [ ] Investigate quotas

**Comment by julienchastang** [comment]
Python related stuff will be moving to its own top-level repository, at some point.
